// !!!!! This file is auto-generated by cmd/gen-settings.ts

/* Copyright 2022 the SumatraPDF project authors (see AUTHORS file).
   License: Simplified BSD (see COPYING) */

struct CoverExample {
    //
    Vec<float>* features;
    //
    bool good;
};

struct CoverChoice {
    //
    Str bookId;
    //
    Str kind;
    //
    int page;
    //
    Vec<float>* rect;
    //
    Str fromPath;
};

struct CoverStore {
    //
    int version;
    //
    Vec<float>* weights;
    //
    Vec<CoverExample*>* coverExamples;
    //
    Vec<CoverChoice*>* coverChoices;
};

#ifdef INCLUDE_COVERSTORE_METADATA

static const FieldInfo gCoverExampleFields[] = {
    {offsetof(CoverExample, features), SettingType::FloatArray, 0},
    {offsetof(CoverExample, good), SettingType::Bool, false},
};
static const StructInfo gCoverExampleInfo = {sizeof(CoverExample), 2,    gCoverExampleFields,
                                             "Features\0Good",     "\0", false};

static const FieldInfo gCoverChoiceFields[] = {
    {offsetof(CoverChoice, bookId), SettingType::String, (intptr_t)""},
    {offsetof(CoverChoice, kind), SettingType::String, (intptr_t)""},
    {offsetof(CoverChoice, page), SettingType::Int, 0},
    {offsetof(CoverChoice, rect), SettingType::FloatArray, 0},
    {offsetof(CoverChoice, fromPath), SettingType::String, (intptr_t)""},
};
static const StructInfo gCoverChoiceInfo = {
    sizeof(CoverChoice), 5, gCoverChoiceFields, "BookId\0Kind\0Page\0Rect\0FromPath", "\0\0\0\0", false};

static const FieldInfo gCoverStoreFields[] = {
    {offsetof(CoverStore, version), SettingType::Int, 1},
    {offsetof(CoverStore, weights), SettingType::FloatArray, 0},
    {offsetof(CoverStore, coverExamples), SettingType::Array, (intptr_t)&gCoverExampleInfo},
    {offsetof(CoverStore, coverChoices), SettingType::Array, (intptr_t)&gCoverChoiceInfo},
};
static const StructInfo gCoverStoreInfo = {
    sizeof(CoverStore), 4, gCoverStoreFields, "Version\0Weights\0CoverExamples\0CoverChoices", "\0\0\0", false};

#endif
