//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SumatraPDF.rc
//
#define IDI_SUMATRAPDF 1

#define IDC_CURSORDRAG 132
#define IDD_PROPSHEET_PRINT_ADVANCED 139
#define IDD_DIALOG_PARTITION_NAME 144

#define IDC_MENUBAR 1016
#define IDC_MENUBAR_REBAR 1018
#define IDC_SECTION_PRINT_RANGE 1050
#define IDC_PRINT_RANGE_ALL 1051
#define IDC_PRINT_RANGE_EVEN 1052
#define IDC_PRINT_RANGE_ODD 1053
#define IDC_SECTION_PRINT_SCALE 1060
#define IDC_PRINT_SCALE_SHRINK 1061
#define IDC_PRINT_SCALE_FIT 1062
#define IDC_PRINT_SCALE_NONE 1063
#define IDC_PRINT_SCALE_STRETCH 1064
#define IDC_PRINT_CENTER_HORIZONTALLY 1065
#define IDC_PRINT_PAPER_SOURCE_BY_SIZE 1066
#define IDC_PRINT_PER_PAGE_PAPER_SIZE 1067
#define IDC_PRINT_ROTATE_LABEL 1068
#define IDC_PRINT_ROTATE 1069
#define IDC_SECTION_PRINT_COMPATIBILITY 1070
#define IDC_PARTITION_NAME_EDIT 1085
#define IDC_PARTITION_NAME_LABEL 1086
#define IDB_RELOADING_CUE 2010

#define IDD_DIALOG_RENAME_SERIES 145
#define IDD_DIALOG_BOOK_METADATA 146
#define IDC_RENAME_SERIES_LABEL 1087
#define IDC_RENAME_SERIES_EDIT 1088
#define IDC_BOOK_TITLE_LABEL 1090
#define IDC_BOOK_TITLE_EDIT 1091
#define IDC_BOOK_TITLE_SOURCE 1092
#define IDC_BOOK_AUTHOR_LABEL 1093
#define IDC_BOOK_AUTHOR_EDIT 1094
#define IDC_BOOK_AUTHOR_SOURCE 1095
#define IDC_BOOK_SERIES_LABEL 1096
#define IDC_BOOK_SERIES_EDIT 1097
#define IDC_BOOK_SERIES_SOURCE 1098
#define IDC_BOOK_YEAR_LABEL 1099
#define IDC_BOOK_YEAR_EDIT 1100
#define IDC_BOOK_YEAR_SOURCE 1101
#define IDC_BOOK_PATH_LABEL 1102
#define IDC_BOOK_REVERT_TITLE 1110
#define IDC_BOOK_REVERT_AUTHOR 1111
#define IDC_BOOK_REVERT_SERIES 1112
#define IDC_BOOK_REVERT_YEAR 1113
#define IDC_BOOK_CLEAR_OVERRIDES 1115

#define IDC_STATIC (-1)

#define IDR_DLL_PAK 1
// translations.txt + marked.min.js + mermaid.min.js + in-app manual (.work/embedded.dat)
#define IDR_EMBEDDED_PAK 2

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 147
#define _APS_NEXT_COMMAND_VALUE 32771
#define _APS_NEXT_CONTROL_VALUE 1114
#define _APS_NEXT_SYMED_VALUE 110
#endif
#endif
